services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=patriciu
      - MONGO_INITDB_ROOT_PASSWORD=bogatu

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=patriciu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bogatu
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}