spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/apiquest
    username: patriciu
    password: bogatu
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


server:
  port: 8081



apiquest:
  jwt:
    secretSigningKey: 582A2489FCFF3AA72A86ED82D43DE469
    expiration: 300000
    refreshToken: 604800000

