
ALTER TABLE Users DROP COLUMN type;


CREATE TABLE Roles(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);


INSERT INTO Roles(name) VALUES('ROLE_ADMIN');
INSERT INTO Roles(name) VALUES('ROLE_USER');
INSERT INTO Roles(name) VALUES('ROLE_CONFIRMED_USER');

ALTER TABLE Users ADD COLUMN role_id INT NOT NULL REFERENCES Roles(id);

